apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  labels:
    app: test-webapp
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: test-webapp
    tier: frontend
  type: LoadBalancer